language: c

env:
  - phpver=5.6.6 phpint=64
  - phpver=5.6.6 phpint=32 phplfs=1
  - phpver=5.6.6 phpint=32
  - phpver=5.5.22 phpint=64
  - phpver=5.5.22 phpint=32 phplfs=1
  - phpver=5.5.22 phpint=32
  - phpver=5.4.38 phpint=64
  - phpver=5.4.38 phpint=32 phplfs=1
  - phpver=5.4.38 phpint=32
  - phpver=5.3.29 phpint=64
  - phpver=5.3.29 phpint=32 phplfs=1
  - phpver=5.3.29 phpint=32

install:
  - . travis/install-apt.sh
  - . travis/compile-php.sh
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php-$phpver/sapi/cli/php -r "var_dump(PHP_INT_SIZE);"
  - truncate -s 5G test.bin
  - php-$phpver/sapi/cli/php -r "var_dump(filesize('test.bin'));"
  - php-$phpver/sapi/cli/php vendor/bin/phpunit

matrix:
  fast_finish: true
