language: php

cache:
  directories:
    - php-5.6.8-64-0
    - php-5.6.8-32-1
    - php-5.6.8-32-0
    - php-5.5.24-64-0
    - php-5.5.24-32-1
    - php-5.5.24-32-0
    - php-5.4.40-64-0
    - php-5.4.40-32-1
    - php-5.4.40-32-0
    - php-5.3.29-64-0
    - php-5.3.29-32-1
    - php-5.3.29-32-0
    - proot
    - rootfs-amd64
    - rootfs-i386
    - vendor
    - xdebug-2.2.7-php-5.6.8-64-0
    - xdebug-2.2.7-php-5.6.8-32-1
    - xdebug-2.2.7-php-5.6.8-32-0
    - xdebug-2.2.7-php-5.5.24-64-0
    - xdebug-2.2.7-php-5.5.24-32-1
    - xdebug-2.2.7-php-5.5.24-32-0
    - xdebug-2.2.7-php-5.4.40-64-0
    - xdebug-2.2.7-php-5.4.40-32-1
    - xdebug-2.2.7-php-5.4.40-32-0
    - xdebug-2.2.7-php-5.3.29-64-0
    - xdebug-2.2.7-php-5.3.29-32-1
    - xdebug-2.2.7-php-5.3.29-32-0

env:
  global:
    - phpxdebugver=2.2.7
  matrix:
    - phpver=5.6.8 phpint=64 phplfs=0
    - phpver=5.6.8 phpint=32 phplfs=1
    - phpver=5.6.8 phpint=32 phplfs=0
    - phpver=5.5.24 phpint=64 phplfs=0
    - phpver=5.5.24 phpint=32 phplfs=1
    - phpver=5.5.24 phpint=32 phplfs=0
    - phpver=5.4.40 phpint=64 phplfs=0
    - phpver=5.4.40 phpint=32 phplfs=1
    - phpver=5.4.40 phpint=32 phplfs=0
    - phpver=5.3.29 phpint=64 phplfs=0
    - phpver=5.3.29 phpint=32 phplfs=1
    - phpver=5.3.29 phpint=32 phplfs=0

install:
  - travis/install.sh

script:
  - travis/script.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  fast_finish: true
